site_name: EntityEngine Docs
site_description: Documentation for EntityEngine, an entity-component-system framework for game development with luau.
site_url: https://https://pizzalvr49.github.io/EntityEngine/
theme:
  name: material
