site_name: EntityEngine Docs
site_description: Documentation for EntityEngine, an entity-component-system framework for game development.
site_url: https://mydomain.org/mysite
theme:
  name: material
